NAME: InterGen
NUM_LAYERS: 8
NUM_HEADS: 8
DROPOUT: 0.1
INPUT_DIM: 262
LATENT_DIM: 1024
FF_SIZE: 2048
ACTIVATION: gelu
CHECKPOINT_INTERACTION: checkpoints/in2IN/epoch=1999-step=352000.pt
CHECKPOINT_INDIVIDUAL: checkpoints/DualMDM/epoch=1999-step=728000.pt

DIFFUSION_STEPS: 1000
BETA_SCHEDULER: cosine
SAMPLER: uniform

MOTION_REP: global
FINETUNE: False

TEXT_ENCODER: clip
T_BAR: 700

CONTROL: text
STRATEGY: ddim50

CFG_WEIGHT_INDIVIDUAL: 2.5
CFG_WEIGHT_INTERACTION: 3.5
W_FUNC: exp
W_VALUE: 0.0085