NAME: InterCLIP
NUM_LAYERS: 8
NUM_HEADS: 8
DROPOUT: 0.1
INPUT_DIM: 258
LATENT_DIM: 1024
FF_SIZE: 2048
ACTIVATION: gelu

MOTION_REP: global
CHECKPOINT: checkpoints/evaluator/interclip.ckpt
FINETUNE: False
EXTENDED: True
