GENERAL:
  EXP_NAME: in2IN
  CHECKPOINT: ./checkpoints
  LOG_DIR: ./log

TRAIN:
  LR: 1e-4
  WEIGHT_DECAY: 0.00002
  BATCH_SIZE: 32
  EPOCH: 2000
  STEP: 1000000
  LOG_STEPS: 10
  SAVE_EPOCH: 50
  RESUME: 
  NUM_WORKERS: 4
  MODE: finetune
  LAST_EPOCH: 0
  LAST_ITER: 0
